### PR TITLE
Add requirements section

### PR DESCRIPTION
**Pull request by xmclark**
Added a requirements section. What else should be added or clarified?

### CODE REVIEW

**Comment by xmclark** [comment]
Related to #19

**Comment by DannyPeck** [comment]
Great work!  Should we add something about how we use Zenhub to manage our development lifecycle?  However, that is more of a contribution / collaborative issue than simply using the software.

**Comment by xmclark** [comment]
@DannyPeck I think that ZenHub comments should go in the Contributing file since ZenHub is more releated to contributing to the project. 

I think the requirements section should be for dependencies and build comments. 

I think a small comment about ZenHub is ok though :) I will add it. 
EDIT:
On Second thought, I think I will create a new issue for documenting ZenHub because issue #19 specifically addresses compiler requirements (event though dependencies are also addressed). 

See PR #36

**Comment by DannyPeck** [comment]
Ok great!  I will check that out, and I agree with you about adding that to the Contributing file.  And instead of leaving a comment about Zenhub in the requirements we should probably just add a statement / section linking to the Contributing.md file and saying for any information on contributing go here.

**Comment by DannyPeck** [comment]
What are we currently waiting on for this PR?

**Comment by xmclark** [comment]
We were waiting for me to finally sit down at my computer to click the magic merge pull request button

**Pull request merged**
