### PR TITLE
Fix time deprecated warnings 45

### PR DESCRIPTION
**Pull request by xmclark**
### Changes proposed within this pull request:
- Add time library to get local time cross-platform
- Update logger class to use time library

### CODE REVIEW

**Comment by xmclark** [comment]
I implemented the `getCurrentTime` function using the windows "safe" local time function and the Linux/apple "safe" local time function with pound-ifde. 

Since I'm running on Windows, I will need people to build on the other platforms to make sure it compiles.

**Comment by xmclark** [comment]
An obviously, I will keep this branch updated with any changes to the build-system branch and will only merge when it has merged.

**Comment by xmclark** [comment]
I talked with Danny and I'm going to merge back to the build system branch.

**Review by technetos — APPROVED** [review]

**Comment by xmclark** [comment]
Wow this is outdated. Anybody have any issues with merging to issue22-build-system? Going to do it at end of day, unless I hear something.

**Review by DannyPeck — APPROVED** [review]
Everything looks good!  Good job factoring out the Time library!

**Comment by DannyPeck** [comment]
This is good to be merged, go for it @xmclark

**Comment by technetos** [comment]
Merge.

**Comment by technetos** [comment]
Im merging this **today** unless anyone has reason not to.

**Pull request merged**
